---
title: "From push press to push jerk: does sex influence the movement pattern?"
author: "Stan Brouwer"
date: 04-19-2024
format:
  html:
    toc: true
    embed-resources: true
#    page-layout: full
editor: source
---

## Introduction

The ability to generate high power -the product of force and velocity- is essential for both daily activities and occupational tasks. It is widely acknowledged to be correlated with overall good health, and retaining power is considered a significant indicator of healthy ageing. Moreover, in the real of sports, power output is regarded as a strong determinant of athletic success. Consequently, the evaluation of muscular power and the development of training strategies aimed at enhancing power are of considerable interest to sport coaches, healthcare workers and researchers alike, and is reflected in the considerable attention focused on the development of power in athletes, and the research examining specific techniques used to maximize power development. 

Exploratory investigations have delved into the power performances across various athletic disciplines, reporting Olympic weightlifting (OLY) as one of the disciplines where athletes demonstrated some of the highest absolute and relative peak power outputs. Consequently, OLY has been proposed as an effective means of enhancing peak power capacities. OLY involves lifting a loaded barbell off the ground to an overhead locked position, in either the Clean and Jerk (C&J) or Snatch, requiring high force in limited time to overcome gravity (5)

These assertions are supported by the biomechanical mechanics inherent to OLY exercises. Firstly, OLY exercises mimic sport-specific movements by engaging in forceful triple extension patterns involving the hips, knees and ankles. Secondly, they facilitate the generation of high rates of force development and power output. 

Further justification for the inclusion of OLY exercises in training programs is provided by research highlighting correlations between OLY performance and various athletic attributes. Studies have shown significant associations between the hang power clean and sprinting (r = -0.58, p<0.01), jumping (r=0.41, p < 0.05) and change of direction tasks (r = -0.41, p < 0.05). Additionally, a recent meta-analysis emphasis the efficacy of incorporating OLY exercises and their derivatives into training  regimens, particularly in improving jumping performance compared to traditional resistance training, with a notable ~5% difference  (effect size [ES] = 0.64, p < 0.001) (Hackett et al., 2016).

Studies have delved into the mechanics underlying these correlations. OLY exercises trigger hormonal responses similar to those observed following conventional strength and hypertrophy protocols. Additionally, cross-sectional data suggests that OLY training induces a transformation from type IIX to type-IIA muscle fibers, accompanied by hypertrophy specifically in type II fibers. This transfer confers advantages for maximal force production. As a result, weightlifters exhibit approximately 15-20% higher isometric peak force and a 13-16% faster contractile rate of force development compared to other strength and power athletes.<unique aspects of weightlifting>

Furthermore, OLY training has been found to reduce the typical sex-related gap in neuromuscular strength and power expression. However, this apparent sex-related difference seems to amplify with advancing adult age, revealing that women undergo a more pronounced age-related decline in muscle shortening velocity and peak power output when compared with men. 

Numerous studies have investigated the impact of sex on strength and other indices of musclular performance, consistently reporting lower levels of strength in females, even after accounting for confounding factors such as body weight.
Some research has examined the relationship between shoulder strength and the Push Jerk (PJ), a movement where a barbell is propelled overhead, reporting differences in the ratio between the Strict Press and PJ across sexes. Generally there are three distinct manners of moving a barbell overhead: the Strict Press (SP), where exclusively the upper-limb strength is utilized to move the barbell; The Push Press (PP), involving a slight downward dip to engage the power of the triple extension; or the Push Jerk (PJ), allowing for catching the barbell at a lower position. Studies have indicated differences in the ratio between the SP and PJ across sexes. This has raised the question at what relative intensity movement patters transition from SP to PP, and form PP to PJ, and wether these thresholds differ between males and females. Given that males exhibit a higher SP-to-PJ ratio, it is hypothesized that female will transition to altered movement patterns at lower relative intensities. 

The primary objective of this study is to investigate the relative intensities at which the movement pattern shifts from performing an overhead barbell press to push press, and from a push press to push jerk. Additionally, this study aims to assess the magnitude of these differences between male and female participants. 

## Methods


A within-subject repeated measures research design was used to determine the kinetics of the S2O under different loads, and the corresponding shifts in preferred technique. IMU’s were placed on the right side of the barbell, lower arm, trunk, upper thighs and lower leg. Kinematic data was collected at [x Hz] and filtered with an [filter]

Participants were asked to press progressively loaded barbells overhead and instructed to SP as long as possible before switching to PP, and PP as long as possible before switching to PJ. 

Defining movements
Technical aspects of the exercises have been well documented and defined elsewhere (19, 12). Differentiating visually can be error prone. Therefore, the movement performed is determined by the kinetics of the barbell, trunk, thighs and legs. 

Strict press
Strict presses were defined as those movements where the barbell is pressed overhead in one upward motion, without any (prior) downward motion of the trunk or thighs. The lifter starts with the barbell in front-rack with their preferred grip width. The barbell should be presses overhead by extending the elbows and flexing the shoulders. The legs must not be involved. The lift is not disqualified if the barbell itself has downward motion at some point, as long as it eventually finishes overhead. 

Push press
Generally the same set-up as in the strict press is used, but the movement starts with counter-movement: by dipping down and coming up the lifter can utilize the power of knee and hip extension, which generates additional upwards momentum. Push presses were defined as those movements where the barbell, trunk and possibly thighs have downward momentum proceeding the upward momentum. 

Push jerk
Again, the same general set-up applies, but after accelerating the barbell upward, the athlete dips downward to catch the barbell in a lower position, thus requiring less upward momentum, and then stands up with the bar. PJ were defined as those movements where the momentum of the barbell, trunk or thighs starts downwards, and then reverses three times. 

Testing procedures
Testing started with a warming-up protocol of two sets of 10 repetition of exercise specific drills: airsquats, front squats, SP, PP, PJ). After the warming up the participants were asked to rotate arround their vertical axis once to demarcate the starting of the testing in the IMU’s. Testing started with an empty 20kg barbell for the males, of 15kg barbell for the females, as is standard for olympic weightlifting. Participants were asked to press the barbell overhead, while retaining the SP and PP technique as long as possible. After each successful lift the barbell was loaded with an additional 5kg, unless the participants self-repoted an 1RM PJ of less then 80kg, in which case incremental steps of 2.5kg were used. Each participant was allowed reattempts, but testing stopped after more than two consecutive misses. Rest time between attempts was not allowed to exceed 2 minutes.  

Statistical analysis
An a priori alpha level was set at p <= 0.05. 




